version: '3'
services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: boneva-app
    networks:
      - boneva
    depends_on:
      - mysql

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    container_name: boneva-nginx
    ports:
      - 4004:80
    networks:
      - boneva
    depends_on:
      - app

  mysql:
    image: mysql:latest
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: boneva
      MYSQL_ROOT_PASSWORD: monster88
      MYSQL_USER: fzrsahi
      MYSQL_PASSWORD: monster88
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - boneva

networks:
  boneva:
    driver: bridge

volumes:
  mysql_data:
